theme: jekyll-theme-cayman
title: "Table Discovery in Data Lakes: State-of-the-art and Future Directions"
description: "Sunday, June 18, 1:30 pm – 3:00 pm – SIGMOD 2023, Seattle, WA"
show_downloads: false
github:
  is_project_page: true